title: Tyler Carr
description: > # this means to ignore newlines until "baseurl:"
        The personal site for Tyler Carr
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://tylrcarr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Tyler Carr
tagline: TA at UNC Charlotte
about-description: A programmer from Charlotte, NC. A lot of other things too. # Add Discription
pic: me.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: tylrcarr@gmail.com # Add your Email address
phone: 704 380 7702 # Add your Phone number
website: tylrcarr.github.io # Add your website, do not add http://
linkedin: tylrcarr # Add your Linkedin handle
github: tylrcarr # Add your Github handle
twitter: '@tylrcarr' # Add your Twitter handle

# Tracker
analytics: UA-47694600-1


# Comments
discus-identifier: tylrcarr # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
