name: Keep Supabase Active

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Supabase
        run: |
          curl -I https://ctmtsrafsysqouyzkqqq.supabase.co